name: ExampleApp

settings:
  base:
    PRODUCT_NAME: ExampleApp
    INFOPLIST_FILE: ExampleApp/Supporting Files/Info.plist
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
  configs:
    Debug:
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
    Release:
      IPHONEOS_DEPLOYMENT_TARGET: 15.0

options:
  developmentLanguage: ja
  bundleIdPrefix: org.app.example.u7chan

packages:
  Moya:
    url: https://github.com/Moya/Moya
    from: 13.0.0

targets:
  ExampleApp:
    type: application
    platform: iOS
    sources:
      - ExampleApp
    dependencies:
      - package: Moya

  ExampleAppFake:
    type: application
    platform: iOS
    settings:
      PRODUCT_NAME: ExampleAppFake
    sources:
      - ExampleApp
    dependencies:
      - package: Moya

  ExampleAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      PRODUCT_NAME: ExampleAppTests
      INFOPLIST_FILE: ExampleAppTests/Supporting Files/Info.plist
    sources:
      - ExampleAppTests
    dependencies:
      - target: ExampleApp

schemes:
  ExampleAppDev:
    build:
      targets:
        ExampleApp: all
        ExampleAppTests: [test]
    run:
      environmentVariables:
        - variable: RUN_ENV
          value: DEV
    test:
      config: Debug
      targets:
        - ExampleAppTests
      environmentVariables:
        - variable: RUN_ENV
          value: TEST

  ExampleAppFake:
    build:
      targets:
        ExampleAppFake: all
        ExampleAppTests: [test]
    run:
      environmentVariables:
        - variable: RUN_ENV
          value: FAKE
    test:
      config: Debug
      targets:
        - ExampleAppTests
      environmentVariables:
        - variable: RUN_ENV
          value: TEST
